site_name: Nestipy
docs_dir: site


theme:
  name: material
  palette:
    primary: teal
    accent: teal
  font:
    text: Roboto
  logo: images/nestipy.png
  features:
    - content.code.copy

extra:
  social:
    - icon: material/github
      link: https://github.com/tsiresymila1/nestipy
      name: Github

extra_css:
  - stylesheets/extra.css

plugins:
- search
- mkdocstrings
- offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Usage:
      - Getting started: start.md
#      - Sync ORM Application: sync_orm.md
#      - Async ORM Application: async_orm.md
#      - MongoDB Application: mongodb.md
  - Dynamic Module:
      - Create dynamic module : dynamic.md

  - Available dynamic module: plugin.md
  - SocketIo Gateway : gateway.md
#    - database: database.md
#    - decorators: decorators.md
#    - App: api.md
#  - License: license.md